DROP TABLE IF EXISTS CUSTOMERS_AUD, TOURS_AUD, ATTRACTIONS_AUD, RESERVATIONS_AUD;

CREATE TABLE CUSTOMERS_AUD
(
    EVENT_ID                  BIGINT AUTO_INCREMENT NOT NULL,
    EVENT_DATE                DATETIME              NOT NULL,
    EVENT_TYPE                VARCHAR(10) DEFAULT NULL,
    id                        BIGINT                NOT NULL,
    OLD_NAME                  VARCHAR(255),
    OLD_LASTNAME              VARCHAR(255),
    OLD_EMAIL                 VARCHAR(255),
    OLD_PHONE_NUMBER          INT,
    OLD_ACCOUNT_CREATION_DATE DATE,
    OLD_SUBSCRIBER            BOOLEAN,
    OLD_ACTIVE                BOOLEAN,
    NEW_NAME                  VARCHAR(255),
    NEW_LASTNAME              VARCHAR(255),
    NEW_EMAIL                 VARCHAR(255),
    NEW_PHONE_NUMBER          INT,
    NEW_ACCOUNT_CREATION_DATE DATE,
    NEW_SUBSCRIBER            BOOLEAN,
    NEW_ACTIVE                BOOLEAN,
    PRIMARY KEY (EVENT_ID)
);

CREATE TABLE TOURS_AUD
(
    EVENT_ID           BIGINT AUTO_INCREMENT NOT NULL,
    EVENT_DATE         DATETIME              NOT NULL,
    EVENT_TYPE         VARCHAR(10) DEFAULT NULL,
    id                 BIGINT                NOT NULL,
    OLD_NAME           VARCHAR(255),
    OLD_COUNTRY        VARCHAR(255),
    OLD_DESCRIPTION    VARCHAR(255),
    OLD_START_DATE     DATE,
    OLD_END_DATE       DATE,
    OLD_START_LOCATION VARCHAR(255),
    OLD_END_LOCATION   VARCHAR(255),
    OLD_PRICE_EURO     INT,
    OLD_ACTIVE         BOOLEAN,
    NEW_NAME           VARCHAR(255),
    NEW_COUNTRY        VARCHAR(255),
    NEW_DESCRIPTION    VARCHAR(255),
    NEW_START_DATE     DATE,
    NEW_END_DATE       DATE,
    NEW_START_LOCATION VARCHAR(255),
    NEW_END_LOCATION   VARCHAR(255),
    NEW_PRICE_EURO     INT,
    NEW_ACTIVE         BOOLEAN,
    PRIMARY KEY (EVENT_ID)
);

CREATE TABLE ATTRACTIONS_AUD
(
    EVENT_ID        BIGINT AUTO_INCREMENT NOT NULL,
    EVENT_DATE      DATETIME              NOT NULL,
    EVENT_TYPE      VARCHAR(10) DEFAULT NULL,
    id              BIGINT                NOT NULL,
    OLD_LOCATION_ID INT,
    OLD_CITY        VARCHAR(255),
    OLD_NAME        VARCHAR(255),
    OLD_DESCRIPTION VARCHAR(255),
    OLD_CATEGORY    VARCHAR(255),
    OLD_TITLE       VARCHAR(255),
    OLD_PRICE_EURO  INT,
    OLD_ACTIVE      BOOLEAN,
    NEW_LOCATION_ID INT,
    NEW_CITY        VARCHAR(255),
    NEW_NAME        VARCHAR(255),
    NEW_DESCRIPTION VARCHAR(255),
    NEW_CATEGORY    VARCHAR(255),
    NEW_TITLE       VARCHAR(255),
    NEW_PRICE_EURO  INT,
    NEW_ACTIVE      BOOLEAN,
    PRIMARY KEY (EVENT_ID)
);

CREATE TABLE RESERVATIONS_AUD
(
    EVENT_ID               BIGINT AUTO_INCREMENT NOT NULL,
    EVENT_DATE             DATETIME              NOT NULL,
    EVENT_TYPE             VARCHAR(10) DEFAULT NULL,
    id                     BIGINT                NOT NULL,
    OLD_TOUR_ID            BIGINT,
    OLD_CUSTOMER_ID        BIGINT,
    OLD_RESERVATION_DATE   DATE,
    OLD_PAYMENT_STATUS     ENUM ('PENDING','CONFIRMED','CANCELED'),
    OLD_RESERVATION_STATUS ENUM ('NEW','PENDING','CONFIRMED','CANCELED','CLOSED'),
    OLD_ACTIVE             BOOLEAN,
    NEW_TOUR_ID            BIGINT,
    NEW_CUSTOMER_ID        BIGINT,
    NEW_RESERVATION_DATE   DATE,
    NEW_PAYMENT_STATUS     ENUM ('PENDING','CONFIRMED','CANCELED'),
    NEW_RESERVATION_STATUS ENUM ('NEW','PENDING','CONFIRMED','CANCELED','CLOSED'),
    NEW_ACTIVE             BOOLEAN,
    PRIMARY KEY (EVENT_ID)
);

